Generate authenticate method from AuthenticationRequest
We cannot automatically generate it because the mutability
of the object is wrong

error[E0596]: cannot borrow `credential` as mutable, as it is not declared as mutable